### ISSUE TITLE
Additional Pronoun options

### ISSUE THREAD

**Issue by SonicRPika** [racetimeGG/racetime-app#124]
Racetime currently has three options for pronouns on the site - masculine (he/him), feminine (she/her), and neutral (they/them). While this is good, it doesn't cover everything. Would it be possible to add more options for people who do not identify as one of those three, or multiple.

For example:
1) other pronouns (Ze/Zir, Ze/Hir, Xe/Xem, Fae/Faer etc)
2) she/they and he/they for those who identify as a mix of neutral and feminine/masculine.
3) The option of Any for those who do not have a preference

**Comment by nihonjinrxs** [comment]
Taking a look at this one now.

@SonicRPika From a bit of research to compile a list of options that should be available (good starting points [here](https://uwm.edu/lgbtrc/support/gender-pronouns/) and [here](https://lgbtlifecenter.org/pronouns/)), I've come up with the following list of options:

- none (use name only)
- any (no preference)
- he/him
- she/her
- they/them
- he/they
- she/they
- ae/aer
- e/em
- fae/faer
- per/per
- ve/ver
- xe/xem
- ze/hir
- zie/hir

I'm going to put together a PR for this shortly. I'm also removing the "descriptive" text displayed in the choice list, as it's likely more harmful than helpful with the expanded list of options.

Let me know if this seems correct, or if I've missed anything here. Happy to update accordingly.

**Comment by deains** [comment]
Hey folks, I'd like to weigh in on this a little before we commit changes to the site. We've had some discussion in the staff room about this, and of course we want to support choice of identity. We also need to support accessibility, which for me personally is one of the fundamental points of the site. It's in the name of accessibility that I think this list needs changing.

Few to none of the pronouns following he/they are in common usage, even in the English-speaking world. I think that including these would lead to more confusion than useful info, especially for users whose first language isn't English. The site should try and be as plain and clear in its use of language as possible. I think rolling these up into "other/ask!" would be best for now, and confine the listed options to well-understood English words.

Also suggesting we use "other/ask!" instead of "any (no preference)" as the latter is simply too long to fit on the site layout.

I hope that we can reach consensus on this. I'm happy to discuss further what the best course of action is. And of course, we can and should revisit this list again in the future. 👍

**Comment by SonicRPika** [comment]
I can understand that, with some more niche non-binary pronouns, that it would confuse more than help if they were an option. But I also feel that being able to identify better with the right pronouns would be useful. It's a difficult line to walk, and I only suggested other neutral pronouns to help with inclusivity.

I think an "Other/Ask!" is a nice idea for the more niche options, as a good middle-ground between having every pronoun option and every combination, and not being able to use the right pronouns for yourself.

Would it be better if, instead of just having the options be a list to choose from, there be a textbox where you can input your preferred pronouns if you select "Other/Ask!"? To prevent abuse, there could be a list of words that the site can look for to approve it so that, if someone identifies as xe/xem, they can use those pronouns. It would also allow for people, in the case of he/them and she/them, be able to swap the words around if they prefer neutral pronouns (so be they/him or they/her).

**Comment by nihonjinrxs** [comment]
Happy to update this PR to whatever the consensus is.

@deains would you be OK with the textbox idea?

For now, I'll go ahead and implement the "Other/Ask!" idea and we can update from there.

**Comment by deains** [comment]
> I can understand that, with some more niche non-binary pronouns, that it would confuse more than help if they were an option. But I also feel that being able to identify better with the right pronouns would be useful. It's a difficult line to walk, and I only suggested other neutral pronouns to help with inclusivity.

I definitely get that, and of course accessibility doesn't just mean easy to understand, it means the site should be welcoming for everyone.

> Would it be better if, instead of just having the options be a list to choose from, there be a textbox where you can input your preferred pronouns if you select "Other/Ask!"? To prevent abuse, there could be a list of words that the site can look for to approve it so that, if someone identifies as xe/xem, they can use those pronouns.

I'm in two minds about this to be honest. I still have concerns about the language barrier, and think it would be better if folks used chat for this where it mattered. On the other hand, so long as the choices are aggressively whitelisted to avoid abuse, there shouldn't be any hitch to having these extra options available. 🤔 I'm leaning towards not doing this right now, but monitoring how many use other/ask and the other options on offer and maybe revisiting this again a little later.

I'll probably also post about this in the Discord once we get the PR out and released so others can chime in.
