### ISSUE TITLE
Bug: Un-forfeit causes cancelled game to be reopened

### ISSUE THREAD

**Issue by scaramangado** [racetimeGG/racetime-app#206]
I cancelled [a race](https://racetime.gg/oot/kind-armos-7568) because it was in the wrong game. At that point one player had already forfeited. When they un-forfeited the timer restarted. After they hit "done" the race was finished and automatically set to "not recorded".

I would expect that actions like "done", "forfeit", "undone", "un-forfeit", etc. are not available after a race is cancelled.

It might be important to note, that this is also the player that opened the race.

**Comment by deains** [comment]
When all players forfeit a race it goes into cancelled state by default. Because of that, this bug will have to be a wontfix. In a 1v1 for example where player A forfeits, and player B hits forfeit accidentallly instead of done then B should be able to undo their forfeit even though the race is now in the cancelled state.

I realise it doesn't make sense in the case when a race is cancelled manually, but I can't fix one scenario without breaking the other. And I don't think this situation is common enough to try and rework how the race states are used.
